### ISSUE TITLE
Missing index.html in ell-studio when installing from Git Repository

### ISSUE THREAD

**Issue by btimothy-har** [MadcowD/ell#292]
I'm installing direct from the git URL to catch up on some of the latest commits, but this breaks ell-studio with an Internal Server Error:

```
File "/usr/local/lib/python3.12/site-packages/starlette/responses.py", line 330, in __call__
	raise RuntimeError(f"File at path {self.path} does not exist.")
	RuntimeError: File at path /usr/local/lib/python3.12/site-packages/ell/studio/static/index.html does not exist.
```

Not sure if there's a difference between between the Pypi package and the Git code, I can't see an index.html in the repo.

**Comment by MadcowD** [comment]
If you're trying to run in development mode you need to use `--dev` when launching ell studio and run `npm install && npm run start` in the `ell-studio` directory to run the front end. Otherwise if you just want to install and run from git without modifying studio do `python3 build.py` and you can run normally.
