### ISSUE TITLE
Can RAG be integrated into ell?

### ISSUE THREAD

**Issue by GCVulnerability** [MadcowD/ell#314]
Ell is an excellent lightweight framework that facilitates the construction of agents. However, in practical applications, agents are often used in conjunction with RAG. Can the construction of RAG be integrated into ell for easier development?

**Comment by medwang1** [comment]
I think you can check https://github.com/MadcowD/ell/blob/main/examples/rag.py.

**Comment by gwpl** [comment]
new link to examples after refactoring: https://github.com/MadcowD/ell/tree/main/examples/rag

**Comment by gwpl** [comment]
So IMHO 

> Can RAG be integrated into ell?

ELL is GREAT approach how to provide more "lower level" (or "middle level") library, that is not too "low-level" but at the same time gives enough control to do magical things easy!

(Reminds me of ZeroMQ , which philosophy is to be like "lego blocks" to enable programmer to easily make whatever they want instead of big collossus message passing solutions like most others... anyway)

Given that, to me personally as user, `ell-ai` feels more like natural fit, of a library to 

* Help make you , your own RAG
* or Someone Make separate Libraries/Solutions that integrate easily with / use ell-ai

Rather then overbloating `ell-ai`.

I believe as user that `ell-ai` will serve us better if will stay scopes on , already big coding task,
and focus to be robust in what's doing (KISS philosophy), rather then try to have "all features and high level functionalities" , that can be build successfully using it and provided by others (therefore helping to grow ell ecosystem).
